releases:
  initial:
    release:
      channel: stable
      version: "4.6"
  latest:
    candidate:
      product: ocp
      stream: ci
      version: "4.7"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: metal-ipi-upgrade-e2e-46-stable-to-47-ci
  cron: 0 */6 * * *
  steps:
    cluster_profile: packet
    env:
      DEVSCRIPTS_CONFIG: |
        IP_STACK=v4
        NETWORK_TYPE=OpenShiftSDN
      RUN_UPGRADE_TEST: "true"
    workflow: baremetalds-e2e-upgrade
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ocp-4.7-ci
